name: test on replicated

on:
  push:
    branches:
      - main

jobs:
  compatibility-matrix:
    strategy:
      fail-fast: false
      matrix:
        cluster: [ {distribution: kind, version: v1.25.3}, {distribution: kind, version: v1.26.3}]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install stackablectl & beku & kuttl
        run: |
          wget --no-verbose https://github.com/stackabletech/stackable-cockpit/releases/download/stackablectl-23.11.1/stackablectl-x86_64-unknown-linux-gnu
          chmod +x stackablectl-x86_64-unknown-linux-gnu
          pipx install beku-stackabletech
          wget --no-verbose https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_linux_x86_64
          chmod +x kubectl-kuttl_0.15.0_linux_x86_64
          echo $PATH
          sudo mv kubectl-kuttl_0.15.0_linux_x86_64 /usr/bin/kuttl
          PATH=/usr/bin/kuttl:$PATH
          echo $PATH
          kubectl kuttl version

      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/replicated-actions/create-cluster@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          cluster-name: ${{ github.ref_name }}-${{ matrix.cluster.distribution }}-${{ matrix.cluster.version }}
          timeout-minutes: 2
          ttl: 30m

      - name: Setup stackable data platform
        run: |
          ./stackablectl-x86_64-unknown-linux-gnu op in secret commons listener zookeeper

      - name: Run a test
        # mask the kubeconfig so it doesn't show up in the logs
        run: |
          scripts/run_tests.sh --parallel 2

      - name: Remove Cluster
        if: always()
        id: remove-cluster
        uses: replicatedhq/replicated-actions/remove-cluster@v1
        continue-on-error: true # It could be that the cluster is already removed
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
